title: Introductory and Intermediate Computing for Data Science 2021
description: Prep material for the Data Science MSc. at Barcelona Graduate School of Economics. All source files, included slides, are available in the Github repository.
theme: jekyll-theme-hacker
